# Generated by Django 2.0.3 on 2019-03-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('readdir', 'can see dir and camera'),)},
        ),
    ]
